function plotPresetCrossections(obj,dset)
    % setup datasets
    datasets = {    'bpeSurfaceResults',...
                    'entireSurfaceResults',...
                    'zetaPlaneResults',...
                    'bulkBoundaryResults',...
                    'centralCrossectionResults',...
                    'centralDDLCrossectionResults',...
                    'leftBpeEdgeCrossectionResults',...
                    'rightBpeEdgeCrossectionResults',...
                    'halfDebyeLengthResults'};
%                     'weResults',...
%                     'ceResults',...
%                     'cathodeCrossectionResults',...
%                     'anodeCrossectionResults',...
    xexp = { 'x','x','x','x','y','y','y','y','x'};
    nDatasets = numel(datasets);
    
%     obj.m.result('multiPurpose1dPlotGroup').set('data',dset);
    obj.updateDatasets(dset);

    for i=1:nDatasets
        obj.plotAlongCrossection(datasets{i},xexp{i});
    end
end