function plotPresetCrossections(obj,dset)
    % setup datasets
    datasets = {    'bpeSurfaceResults',...
                    'entireSurfaceResults',...
                    'zetaPlaneResults',...
                    'bulkBoundaryResults',...
                    'weResults',...
                    'ceResults',...
                    'centralCrossectionResults',...
                    'centralDDLCrossectionResults',...
                    'leftBpeEdgeCrossectionResults',...
                    'rightBpeEdgeCrossectionResults',...
                    'cathodeCrossectionResults',...
                    'anodeCrossectionResults',...
                    'halfDebyeLengthResults'};
    nDatasets = numel(datasets);
    
%     obj.m.result('multiPurpose1dPlotGroup').set('data',dset);
    obj.updateDatasets(dset);

    for i=1:nDatasets
        obj.plotAlongCrossection(datasets{i});
    end
end